[build]
  base = "frontend"
  command = "npm install && chmod +x node_modules/.bin/react-scripts && npm run build"
  publish = "frontend/build"

[build.environment]
  REACT_APP_API_URL = "https://medai-wlfd.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"